blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateViews, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogCreateViews.as_view(), name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),   # <int:pk>/ hace referencia al ID del Post. int (entero), pk(privateKey)
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),   # El name o namespace sera relevante cuando queramos llamar las urls desde los templates

    path('blog/', include('blog.urls', namespace='blog')) # Incluyo del folder 'blog' el archivo 'urls.py'
]

blog/models.py
from django.db import models

# Los modelos nos permiten editar la informacion de manera dinamica: leer, borrar, actualizar, crear
# Los models son la informacion que se envia a la base de datos
# Las migraciones son los cambios que hacemos en el archivo de models.py

class Post(models.Model):   # Cada Post que creemos a su vez tendra un ID al cual podremos acceder para buscar un Post especifico
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):        # Para que el Post se muestre con el title que le pusimos.
        return self.title     # self hace referencia a Post

blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):   # Formulario para crear un Post
    class Meta:
        model = Post   # Aca definimos el modelo que vamos a usar. En este caso importamos Post del archivo models.py
        fields = ('title', 'content')   # Los campos que hayamos definido en el model Post

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()   # Traemos todos los Posts
        context={
            'posts':posts  
        }
        return render(request, 'blog_list.html', context)   # Retorna el request, en el html solicitado, con el context


class BlogCreateViews(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()   # Traigo el PostCreateForm dentro de esta variable para poder agregarlo al context
        context = {
            'form':form   # Una vez agregado al context me aparecera en la vista en linea
        }
        return render(request, 'blog_create.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method=="POST":   # Hace referencia al <form> de blog_create con method="POST"
            form = PostCreateForm(request.POST)   # 1ro traemos el PostCreateForm y le pasamos la inf dentro de POST
            if form.is_valid():   # Si el form es valido...
                title = form.cleaned_data.get('title')   # Obtengo los datos que ingresaron en 'title'
                content = form.cleaned_data.get('content')   # Obtengo los datos que ingresaron en 'content'

                p, created = Post.objects.get_or_create(title=title, content=content)   # p, viene de post. Con la info del form, crearemos un Post.   El title y content en rojo vienen del model Post, y los otros de esta funcion
                p.save()
                return redirect('blog:home')   # Redirijo al home

        context={
            
        }
        return render(request, 'blog_create.html', context)


class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):   # Agrego el pk
        post = get_object_or_404(Post, pk=pk)   # Llamo un post especifico
        context={
            'post':post
        }
        return render(request, 'blog_detail.html', context)


class BlogUpdateView(UpdateView):
    model=Post
    fields=['title', 'content']
    template_name='blog_update.html'

    # Vuelvo a blog_detail ya actualizado
    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})


class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url= reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% tailwind_css %}

    <title>Document</title>

</head>
<body>

    {% block content %}{% endblock content %}   <!-- Esto nos permite pasar la config a las otras vistas-->



</body>
</html>

templates/blog_create.html
<form method="POST">
{% csrf_token %}   <!--Siempre que hacemos un form tenemos que agregar este {% csrf_token %}-->
title{{form.title}}   <!-- 'form' hace referencia al context que le pase a la vista de BlogCreateView -->
<br>   <!-- break -->
content{{form.content}}
<button type="submit">Submit</button>
</form>

templates/blog_delete.html
Are you sure?
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Delete</button>
    </form>

templates/blog_detail.html
<!--Muestro los fields del post-->
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
{% extends 'base.html' %}

{% block content %}
blog list
<br>
{%for post in posts%}   <!--Solo aparecen estas opciones si existe algun post-->
<a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
<a href="{% url 'blog:update' post.id %}">Update</a>
<a href="{% url 'blog:delete' post.id %}">Delete</a>
{%endfor%}
<br>
<a class="inline-flex items-center px-2.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href='{% url 'blog:create' %}'>Create</a>

{% endblock content %}

templates/blog_update.html
<!-- Es igual al blog_create.html, pero cambiamos lo que dice el Button-->
<form method="POST">
{% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<button type="submit">Update</button>
</form>

templates/index.html
{% extends 'base.html' %}

{% block content %}Hola, visita mi <a class="text-blue-500" href="{%url 'blog:home' %}"> blog aqui</a>{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>